file<-read.csv("US_data.csv",head=TRUE) #reading the file of US Flu data
attach(file) # attaching the file
model<-lm(HHS.Region.7..IA..KS..MO..NE.~Iowa+Kansas+Missouri+Nebraska) # finding the linear regression on region 7 with the states Iowa, Kansas, Missouri , Nebraska  
summary(model) # finding the summary of linear regression 
#Reference : World Flu Data - https://www.google.org/flutrends/about/data/flu/us/data.txt
US_data <- read.csv(file.choose(),head=TRUE,sep=",") 
#reading the file to US_data
US_data ["ID"] <- seq(from=1,to=length(US_data$SN),by=1)
#creating a sequence SN corresponding to each date.
attach(US_data)
plot(US_data$ID,Massachusetts,pch=20) 
#plotting the ID vs Massachusetts
points(US_data$ID,Boston..MA,col="red",pch=20)
#plotting the ID vs Boston
points(US_data$ID,Sommerville..MA,col="blue",pch=20)
#plotting the ID vs Sommerville
#Code:attach(US_data)
plot(SN,(Iowa+Kansas+Missouri+Nevada)/4,col="blue",pch=20)
#Here I plotted the SN vs the mean of HHS region 7.
attach(US_data)
points(SN,HHS.Region.7..IA..KS..MO..NE.,col="red",pch=20)
#References:US_Data :https://www.google.org/flutrends/about/
library(XML) # Calling the required packages.
install.packages("RCurl") # Installing the requred package.
library(RCurl)
install.packages("sqldf")
library(sqldf)
k<-readHTMLTable(getURL("https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population"),which=1,stringsASFactors=F) # Reading the table from the link .
k
View(k)
k1<-k[,3:4]
View(k1)
US_state=data.frame(file)
US_state=US_state[c(589:620),c(2:52)]
View(US_state)
datastate<-apply(US_state,2,function(x)max(x,na.rm=TRUE))
View(datastate)
dataset1<-data.frame(datastate)
new_df<-dataset1[order(row.names(dataset1)),]
new_df<-data.frame(new_df)
View(new_df)
state_pop<-read.table(file.choose(),sep=",", head=F)
state_popdf<-data.frame(state_pop)
state_popdf1<-state_pop[,c(5,12)]         
View(state_popdf1)
state_popdf1<-state_pop[,c(5,13)]
state_popdf2<-state_popdf1[order(state_popdf1[,1]),]
View(state_popdf2)
datasetplot2<-sqldf("select * from state_popdf2 where V5 not in('Midwest Region','Northeast Region','Puerto Rico','South Region','West Region','United States')")
View(datasetplot2)
plot(new_df$new_df,datasetplot2$V13,ylab="population", xlab="flu trends")
world_data2<-read.csv(file.choose(),head=FALSE,sep=",",skip='627')
header<-read.csv(file.choose(),head=FALSE,sep=",",nrows=1,stringsAsFactors=FALSE)
colnames(file2)<-unlist(header)
m<-apply(file2,2,function(x)max(x,na.rm=TRUE))
df<-data.frame(m)
df1=data.frame(df[-1,])
View(df1)
install.packages("sqldf")
library(sqldf)
countrlatitude=read.csv.sql(file.choose(),'SELECT Latitude FROM file where country in(\"AR\",\"AU\",\"AT\",\"BE\",\"BO\",\"BR\",\"BG\",\"CA\",\"CL\",\"FR\",\"DE\",\"HU\",\"JP\",\"MX\",\"NL\",\"NZ\",\"NO\",\"PY\",\"PE\",\"PL\",\"RO\",\"RU\",\"ZA\",\"ES\",\"SE\",\"CH\",\"UA\",\"US\",\"UY\")')
plot(df1$df..1...,countrlatitude$latitude)
install.packages("XML") # Installing the necessary packages 
library(XML) # calling the library
install.packages("RCurl")
library(RCurl)
x<-getURL("http://www.cdc.gov/mmwr/preview/mmwrhtml/mm6401a4.htm?s_cid=mm6401a4_w")  # assigning the URL to a variable 
y<-readHTMLTable(x,header=T,which=1,stringASFactors=F) # reading the table present in the variable which results in the whole table. 
z<-readHTMLTable(x,header=T,which=2,stringASFactors=F) # separating the required table of vaccine status data from the whole table.
View(z)
View(y)
y1<-data.frame(y$V1)
y1[,"No"]<-data.frame(y$V7)
y1[,"Total"]<-data.frame(y$V8)
y1[,"%"]<-data.frame(y$V9)
y1[,"p value"]<-data.frame(y$V10)
View(y1)
y2<-y1[-1:-3,]
View(y2)
x<-getURL("https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations")
y<-readHTMLTable(x,header=T,which=1,stringASFactors=F)
View(y) # viewing the table.
# Reference:https://en.wikipedia.org/wiki/List_of_U.S._state_abbreviations



